### PR TITLE
Fixing CI

### PR DESCRIPTION
**Pull request by samsonasik**

### CODE REVIEW

**Comment by samsonasik** [comment]
@TomasVotruba do you think new tag is needed for this change https://github.com/rectorphp/rector-laravel/commit/bcc9f60276a2fc4567a94f51e8ce5369d168b180#diff-2cd0c4d0c03ff28f9516f36a8c1602baee2c5ead80a9734ed1cedf67e2b24642 ?

**Comment by TomasVotruba** [comment]
The require-dev is used only here, it does not affect other packages, so not necessary to tag

**Comment by samsonasik** [comment]
@TomasVotruba what I meant is the `NodeFactory` change on 

```
// decorate with namespaced names
        $nameResolver = new NameResolver(null, [
            'replaceNodes' => false,
            'preserveOriginalNames' => true,
        ]);
        $nodeTraverser = new NodeTraverser();
        $nodeTraverser->addVisitor($nameResolver);
        $nodeTraverser->traverse([$class]);
```

which doesn't has new tag yet on https://github.com/rectorphp/rector-laravel/commit/bcc9f60276a2fc4567a94f51e8ce5369d168b180#diff-2cd0c4d0c03ff28f9516f36a8c1602baee2c5ead80a9734ed1cedf67e2b24642

**Comment by TomasVotruba** [comment]
Ah, in that case yes :+1:

**Comment by TomasVotruba** [comment]
Can you manage the tagging?

**Comment by samsonasik** [comment]
Yes, I added rector-laravel tag 0.11.12 https://github.com/rectorphp/rector-laravel/releases/tag/0.11.12

**Pull request merged**
