### PR TITLE
Update

### PR DESCRIPTION
**Pull request by TomasVotruba**
- bump deps
- misc
- remove AddMockConsoleOutputFalseToConsoleTestsRector, as very narrow rule

### CODE REVIEW

**Comment by samsonasik** [comment]
Close re-open to restart build

**Comment by TomasVotruba** [comment]
Could you handle the rest of packages to update composer deps? The naming rule based on type has changed, so the variables has to be updated.

**Comment by samsonasik** [comment]
I will try.

**Comment by TomasVotruba** [comment]
:+1:

**Pull request merged**
